#!/usr/bin/env python3
import time

import colors as c

while True:
    for count in range(12):
        time.sleep(0.375)
        print(c.violet + "badgers")
    for count in range(2):
        time.sleep(0.4)
        print(c.blue + "MUSHROOM")

    for count in range(12):
        time.sleep(0.375)
        print("badgers")
    for count in range(2):
        time.sleep(0.4)
        print(c.red + "MUSHROOM")

    for count in range(12):
        time.sleep(0.375)
        print(c.yellow + "badgers")
    for count in range(2):
        time.sleep(0.4)
        print(c.magenta + "MUSHROOM")
        print(c.green + "SNAKE SNAKE OOOOOOOOOH   ITS A SNAKEEEEE!")
       
