#!/usr/bin/env python3
import time

import colors as c

while True:
    for count in range(12):
        time.sleep(0.375)
        print("badgers")
    for count in range(2):
        time.sleep(0.4)
        print("MUSHROOM")

    for count in range(12):
        time.sleep(0.375)
        print("badgers")
    for count in range(2):
        time.sleep(0.4)
        print("MUSHROOM")

    for count in range(12):
        time.sleep(0.375)
        print("badgers")
    for count in range(2):
        time.sleep(0.4)
        print("MUSHROOM")
        print("SNAKE SNAKE OOOOOOOOOH   ITS A SNAKEEEEE!")
       
