#!/usr/bin/env python3

import colors as c 
print(c.clear)
import random
sides = []
sides.append('''
 -------
|       |
|   0   |
|       |
 -------
''')
sides.append('''
 -------
|0      |
|       |
|      0|
 -------
''')
sides.append('''
 -------
|0      |
|   0   |
|      0|
 -------
''')
sides.append('''
 -------
|0     0|
|       |
|0     0|
 -------
''')
sides.append('''
 -------
|0     0|
|   0   |       
|0     0|
 -------
''')
sides.append('''
 -------
|0  0  0|
|       |
|0  0  0|
 -------
''')
while True:
    side = random.choice(sides)
    print(c.clear + c.rc() + side + c.x)

#sides = ["1","2","3","4","5","6"]

#for side in sides:
   #print("no index needed for", side)

#for n in range(6):
    #print("index", n, "is side", sides[n])


# n = 0
# while n < 6:
#   print("index", n, "is side, sides[n])
