#!/usr/bin/env python3

import random
import colors as c
print(c.clear + "")
print(c.yellow + "WELCOME TO EIGHTBALL ASK AWAY!")

answer = input(c.green + '> ' + c.red)

outcomes = [
'YES',
'NO',
'MAYBE'
]

print(random.choice(outcomes))

