#!/usr/bin/env python3

import colors as c
name = '> '
print(c.clear + "")
print(c.orange + "HELLOW THEY'RE whuts yur name" + c.reset)
answer = input(c.violet + '> ' + c.reset)
print(c.magenta + "HELLOW THEY'RE drew")

