#!/usr/bin/env python3
import colors as c
from utils.sh import ask


print(c.clear)

print("WELCOME... to the APPLEPIE quiz...!")

def q1():
    answer = ask("How many slices are in one normal sized applepie?")
    if answer == "8":
        print("YUR NOT A TOTAL IDIOT YAY!!!!!!!")
        return True
        print("NAH")
        return False

def q2():
    answer = ask("What is applepie's enemy?")
    if answer == "pie-apple":
        print("That one was hard Ill  tone it down a bit :)")
        return True
        print("LEL")
        return False

def q3():
    answer = ask("What is the first and last name of the creator of applepie?")
    if answer == "Drew Gibbs":
        print("YUS YUR SOOOOO SMOOT")
        return True
        print("NAH")
        return False

questions = [q1,q2,q3]

