#!/usr/bin/env python3
import colors as c
print(c.clear + c.orange + "Does thou like waffles?" + c.reset)
answer = input(c.yellow + '> ' + c.green)
print(answer)


if answer == "yes":
    print(c.orange + "Does thou like pancakes" + c.reset)
    answer = input(c.yellow + '> ' + c.green)
    


    if answer == "yes":
        print(c.orange + "Does thou like frenchtoest" + c.reset)
        answer = input(c.yellow + '> ' + c.green)



        if answer == "yes":
            print("doo do do dooo cant wait to get a mouth full!")
            answer = input(c.yellow + '> ' + c.green)

        else:
            print("Well I like frenchtoest")
    else:
        print("Well I like pancakes")
else:
    print("Well I like waffles")
